spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simplemall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


